github.com:
    users:
        nby578:
            oauth_token: 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
    git_protocol: https
    user: nby578
    oauth_token: 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
